version: "3"
services:
  db:
    image: "postgres"
    environment:
      POSTGRES_USER: william
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hansa_dev
    volumes:
      - gorm_provider-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  database-data:
