// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"database/sql"
	"time"
)

type Board struct {
	ID        int64
	Name      string
	GameID    sql.NullInt64
	Width     int32
	Height    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type City struct {
	ID             int64
	BoardID        int64
	Name           string
	X              int32
	Y              int32
	UpgradeOffered int16
	ImmediatePoint int16
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type CitySpace struct {
	ID                int64
	CityID            int64
	Order             int16
	SpaceType         int16
	RequiredPrivilege int16
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type SchemaMigration struct {
	Version string
}
